# Generated by Django 4.1 on 2025-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_activity_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
