# Generated by Django 4.1 on 2025-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0003_leaderboard_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
